config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.estheloan

  constraints host: config[:staff][:host] do
    namespace :staff ,path: config[:staff][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login

      resource :session, only:[ :create, :destroy]

      resource :account

      resource :password, only: [ :show, :edit, :update]

      resources :customers

      resources :customers ,only: [:index] do
         member { get :print}
      end

      resources :loanorders

      resources 'loanorders', only: [:index] do
        collection { post :import }
      end

    end
  end

  constraints host: config[:customer][:host] do
    namespace :customer ,path: config[:customer][:path] do

      get 'login' => 'sessions#new', as: :login
      resource :session, only: [ :create, :destroy]

      resource :customer do
        patch :confirm
      end

      resources :loanorders, only:[ :index]

      resources :loanorders, only:[ :index] do
        collection { get :search}
      end

      resource :password,only: [:show, :edit, :update]
    end
  end

  constraints host: config[:admin][:host] do
    namespace :admin , path: config[:admin][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login
      post 'session' => 'sessions#create', as: :session
      delete 'session' => 'sessions#destroy'
      get 'customers/update_stores', as: 'update_stores'

      resources :staff_members do
        resources :staff_events, only: [:index]
      end
      resources :staff_events, only: [:index]

      resources :customers

      resources :customers ,only: [:index] do
         member { get :print}
      end

      resources :companies do
        resources :companies, only: [:index]
      end

      resources :loanorders

      resources 'loanorders', only: :index do
            collection { post :import }
      end
    end
  end

    root 'errors#not_found'

    get '*anything' => 'errors#not_found'

    

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	include EmailHolder
	include CustomerPersonalNameHolder
  belongs_to :company

	#has_many :orders, class_name: 'Loanorder', dependent: :destroy

	#before_validation do
	#	self.email_for_index = email.downcase if email
	#end	

	validates :company_id,:store_code, :store_name,
  					:email,  presence: true

  validates :start_date, presence: true, date: {
    after_or_equal_to: Date.new(2000, 1, 1),
    before: ->(obj) { 1.year.from_now.to_date },
    allow_blank: true
  }
  validates :end_date, date: {
    after: :start_date,
    before: ->(obj) { 1.year.from_now.to_date },
    allow_blank: true
  }
	#:start_date, presence: true


	#validates :password, presence: true
   #     length:     {within: 6..30}

  has_secure_password

	def active?
		!suspended? && start_date <= Date.today &&
		(end_date.nil? || end_date > Date.today)
	end




	PREFECTURE_NAMES = %w(
    北海道
    青森県 岩手県 宮城県 秋田県 山形県 福島県
    茨城県 栃木県 群馬県 埼玉県 千葉県 東京都 神奈川県
    新潟県 富山県 石川県 福井県 山梨県 長野県 岐阜県 静岡県 愛知県
    三重県 滋賀県 京都府 大阪府 兵庫県 奈良県 和歌山県
    鳥取県 島根県 岡山県 広島県 山口県
    徳島県 香川県 愛媛県 高知県
    福岡県 佐賀県 長崎県 熊本県 大分県 宮崎県 鹿児島県
    沖縄県
    日本国外
  )
  validates :postal_code,format: { with: /\A\d{7}\z/,allow_blank: true}
  validates :prefecture, inclusion: {in: PREFECTURE_NAMES, allow_blank: true}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::Base
 	def index
    #@company = Company.all
    @customer = Customer.joins('INNER JOIN companies ON customers.company_id = companies.company_code')
                        .select('customers.*,companies.company_code,companies.company_name')
    #@customer = Customer.all
    @customer = @customer.page(params[:page])
  end

  def show
    customer = Customer.find(params[:id])
    redirect_to [ :edit, :admin, customer ]
  end
  def print
    @customer = Customer.find(params[:id])
  end
  def new
    @customer = Customer.new
    #@companies = Loanorder.select()
    @loanorders = Loanorder.none
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)

    #@loanorders = Loanorder.select(:store_code, :store_name).uniq.order(:store_code).where("company_code = ?", params[:company_code])
  
    @customer.init_password = password_gen(length=8)
    @customer.password = @customer.init_password
    if @customer.save
      flash.notice = 'お客様情報を新規登録しました。'
      redirect_to :admin_customers
    else
      render action: 'new'
    end
  end

  def update_stores
    @loanorders = Loanorder.select(:store_code, :store_name).uniq.order(:store_code).where("company_code = ?", params[:company_code])
    respond_to do |format|
      format.js
      format.xml {render :xml => @stores}
    end
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.assign_attributes(customer_params)
    #if @customer.valid?
	    if @customer.save
	      flash.notice = 'お客様情報を更新しました。'
	      redirect_to :admin_customers
	    else
	      render action: 'edit'
	    end
	 #else
	 #  	render action: 'edit'
	 # end
  end

  def destroy
    customer = Customer.find(params[:id])
    customer.destroy!
    flash.notice = 'お客様情報を削除しました。'
    redirect_to :admin_customers
  end
  def confirm
    @customer = Customer.new(customer_params)
    if params[:commit]
      if @customer.valid?
        render action: 'confirm'
      else
        flash.now.alert = '入力に誤りがあります。'
        render action: 'new'
      end
    else
        render action: 'new'
    end
  end

  private
  def customer_params
  	params.require(:customer).permit(
  		:company_id, :company_name,:store_code, :store_name,
  		:staff_family_name, :staff_given_name, :staff_family_name_kana, :staff_given_name_kana,
  		:postal_code, :prefecture, :city, :address1, :address2, :telephone_number,
  		:fax_number, :email, :start_date,:end_date,:suspended, :parent_and_child, :password
  		)
  end
end

app/controllers/customer/base.rb
class Customer::Base < ApplicationController

	before_action :authorize
	
	private

	def current_customer
		if session[:customer_id]
			@current_customer ||=
				Customer.find_by(id: session[ :customer_id])
		end
	end

	helper_method :current_customer



	def authorize
  	unless current_customer
  		flash.alert = 'ログインしてください。'
  		redirect_to :customer_login
  	end
  end
	
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < Customer::Base
	skip_before_action :authorize

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash.notice = 'アカウントを新規登録しました。'
      redirect_to :customer_root
    else
      render action: 'new'
    end
  end
  def confirm
    @customer = Customer.new(customer_params)
    if params[:commit]
      if @customer.valid?
        render action: 'confirm'
      else
        flash.now.alert = '入力に誤りがあります。'

        render action: 'new'

      end
    else
        render action: 'new'
    end
  end

  private
  def customer_params
  	params.require(:customer).permit(
  		:company_name, :top_family_name, :top_given_name, :top_family_name_kana, :top_given_name_kana,
  		:staff_family_name, :staff_given_name, :staff_family_name_kana, :staff_given_name_kana,
  		:zip_code, :prefecture, :city, :address1, :address2, :telephone_number, :mobilephone_number,
  		:fax_number, :email, :password
  		)
  end
end

app/controllers/customer/loanorders_controller.rb
class Customer::LoanordersController < Customer::Base
	def index
		@max = Loanorder.maximum(:update_datetime)
		@customer = Customer.where(company_id: session[:company_code])
		@company_code = session[ :company_code]	
		@search_form = Customer::LoanorderSearchForm.new(params[:search])
		#@total = @search_form.search(session[:company_code]).select(sum(application_money))
		@loanorders = @search_form.search(session[ :company_code]).page(params[:page]).per(18)
		@total = @search_form.search(session[ :company_code]).group(:company_id).sum(:application_money)
	end

end

app/controllers/customer/passwords_controller.rb
class Customer::PasswordsController < Customer::Base
	def show
		redirect_to :edit_customer_password
	end
	def edit
    @change_password_form =
      Customer::ChangePasswordForm.new(object: current_customer)
  end

  def update
    @change_password_form = Customer::ChangePasswordForm.new(customer_params)
    @change_password_form.object = current_customer
    if @change_password_form.save
      flash.notice = 'パスワードを変更しました。'
      redirect_to :customer_account
    else
      flash.now.alert = '入力に誤りがあります。'
      render action: 'edit'
    end
  end

  private
  def customer_params
    params.require(:customer_change_password_form).permit(
      :current_password, :new_password, :new_password_confirmation
    )
  end
end

app/controllers/customer/sessions_controller.rb
class Customer::SessionsController < Customer::Base

	skip_before_action :authorize

	def new 
		if current_customer
			redirect_to :customer_loanorders
		else
			@login_form = Customer::LoginForm.new
			render action: 'new'
		end
	end

	def create
    @login_form = Customer::LoginForm.new(params[:customer_login_form])
    if @login_form.valid?
	    if @login_form.email.present?
	      customer = Customer.find_by(email_for_index: @login_form.email.downcase)
	    end
	    if Customer::Authenticator.new(customer).authenticate(@login_form.password)
	    	if customer.suspended?
	    		flash.now.alert = 'アカウントが停止されています。'
	    		render action: 'new'
	    	else
	    		company = Company.where(company_code: customer.company_id).first
	    		if @login_form.remember_me?
	    			cookies.permanent.signed[:customer_id] = customer.id
	    		else
	    			cookies.delete(:customer_id)
	    			session.clear
		        session[:customer_id] = customer.id
	    		end
    			session[:customer_id] = customer.id
	        session[:company_code] = customer.company_id
	        session[:company_name] = company.company_name
	        session[:store_name] = customer.store_name
	        session[:parent_and_child] = customer.parent_and_child
	        flash.notice = 'ログインしました。'
	        redirect_to :customer_loanorders
	      end
	    else
	      flash.now.alert = 'メールアドレスまたはパスワードが正しくありません。'
	      render action: 'new'
	    end
	   else
	   	render action: 'new'
	   	#render text: @form.errors.full_messages[0]
	   end
  end
  def destroy
  	session.delete(:customer_id)
  	session.clear
  	cookies.delete(:customer_id)
  	flash.notice = 'ログアウトしました。'
  	redirect_to :customer_login
  end
end

app/controllers/customer/top_controller.rb
class Customer::TopController < Customer::Base

	skip_before_action :authorize
	def index
		render action: 'index'
	end
end

app/controllers/staff/customers_controller.rb
class Staff::CustomersController < Staff::Base
 	def index
    @customer = Customer.order(:company_name)
    @customer = @customer.page(params[:page])
  end

  def show
    customer = Customer.find(params[:id])
    redirect_to [ :edit, :admin, customer ]
  end
  def print
    @customer = Customer.find(params[:id])
  end
  def new
    @customer = Customer.new
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash.notice = 'お客様情報を新規登録しました。'
      redirect_to :admin_customers
    else
      render action: 'new'
    end
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.assign_attributes(customer_params)
   # if @customer.valid?
	    if @customer.save
	      flash.notice = 'お客様情報を更新しました。'
	      redirect_to :admin_customers
	    else
	      render action: 'edit'
	    end
	 # else
	 #  	render action: 'edit'
	 # end
  end

  def destroy
    customer = Customer.find(params[:id])
    customer.destroy!
    flash.notice = 'お客様情報を削除しました。'
    redirect_to :admin_customers
  end
  def confirm
    @customer = Customer.new(customer_params)
    if params[:commit]
      if @customer.valid?
        render action: 'confirm'
      else
        flash.now.alert = '入力に誤りがあります。'
        render action: 'new'
      end
    else
        render action: 'new'
    end
  end

  private
  def customer_params
  	params.require(:customer).permit(
  		:company_code,:company_name, :top_family_name, :top_given_name, :top_family_name_kana, :top_given_name_kana,
  		:staff_family_name, :staff_given_name, :staff_family_name_kana, :staff_given_name_kana,
  		:zip_code, :prefecture, :city, :address1, :address2, :telephone_number, :mobilephone_number,
  		:fax_number, :email, :password,:start_date,:end_date,:suspended
  		)
  end
end

app/views/admin/customers/_company_select.html.erb
<%= f.collection_select :customer,:store_name, Loanorder.select(:company_code, :company_name,:store_code, :store_name).uniq, :store_code, :store_name %>

app/views/admin/customers/_form.html.erb
<%= markup do |m|
  p = CustomerFormPresenter.new(f, self)
  m << p.notes
  m << p.collection_select_block(:company_id,'加盟店',Company.order(:company_code),:company_code,:company_name,required: true)
  m << p.text_field_block(:store_code, '店舗コード', size: 2, required: true)
  m << p.text_field_block(:store_name, '店舗名', size: 60, required: true)
  m << p.parent_and_child_field_block

  m << p.full_name_block(:staff_family_name, :staff_given_name, '担当者氏名', size: 32, required: true)
  m << p.full_name_block(:staff_family_name_kana, :staff_given_name_kana, '担当者フリガナ', size: 32, required: true)


  m << p.text_field_block(:telephone_number, '電話番号')

  m << p.text_field_block(:email, 'メールアドレス', size: 32 ,required: true)

  m << p.date_field_block(:start_date, '開始日', required: true)
  m << p.date_field_block(:end_date, '終了日', required: false)

  m << p.check_boxes


end %>

app/views/admin/customers/edit.html.erb
<% @title = 'お客様情報の編集' %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_for [ :admin, @customer ] do |f| %>
    <%= render 'form', f: f %>
    <div class="buttons">
      <%= f.submit '更新' %>
      <%= link_to 'キャンセル', :admin_customers %>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<% @title = 'お客様管理' %>
<h1><%= @title %></h1>

<div class="table-wrapper">

  <div class="links">
    <%= link_to '新規登録', :new_admin_customer %>
  </div>

  <%= paginate @customer %>

  <table class="listing">
    <tr>
      <th>ｺｰﾄﾞ</th>
      <th>加盟店名</th>
      <th>ｺｰﾄﾞ</th>
      <th>店舗名</th>
      <th>区分</th>  
      <th>担当者名</th>
      <th>フリガナ</th>
      <th>電話番号</th>
      <th>メールアドレス</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>停止フラグ</th>
      <th>アクション</th>
    </tr>
    <% @customer.each do |m| %>
      <% p = CustomerPresenter.new(m, self) %>
      <tr>

        <td><%= m.company_id %></td>
        <td><%= m.company_name %></td>
        <td><%= m.store_code %></td>
        <td><%= m.store_name %></td>
        <td><%= m.parent_and_child %></td>
        <td><%= m.staff_family_name %> <%= m.staff_given_name %></td>
        <td><%= m.staff_family_name_kana %> <%= m.staff_given_name_kana %></td>

        <td><%= m.telephone_number %></td>
        <td class="email"><%= m.email %></td>
        <td class="date"><%= m.start_date.try(:strftime, '%Y/%m/%d') %></td>
        <td class="date"><%= m.end_date.try(:strftime, '%Y/%m/%d') %></td>
        <td class="boolean"><%= p.suspended_mark %></td>
        <td class="actions">
          <%= link_to '印刷', [ :print, :admin, m ,format: 'pdf'] %> |
          <%= link_to '編集', [ :edit, :admin, m ] %> |
          <%= link_to '削除', [ :admin, m ], method: :delete,
            data: { confirm: '本当に削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= paginate @customer %>

  <div class="links">
    <%= link_to '新規登録', :new_admin_customer %>
  </div>

</div>

app/views/admin/customers/new.html.erb
<% @title = 'お客様情報の新規登録' %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_for @customer ,url: admin_customers_path do |f| %>
    <%= render 'form', f: f %>
    <div class="buttons">
      <%= f.submit '登録' %>
      <%= link_to 'キャンセル', :admin_customers %>
    </div>
  <% end %>
</div>

app/views/admin/customers/save_form.html.erb
<%= f.label :加盟店名 %>
<%= f.collection_select :company_code, Loanorder.select(:company_code, :company_name).uniq, :company_code, :company_name,include_blank: true %></br>
<%= f.label :店舗名 %>
<%= f.select :store_code, options_for_select(@loanorders.collect { |store| [store.store_name,
   store.store_code] },0),{},{ id: 'stores_select'} %>
 
<%= markup do |m|
  p = CustomerFormPresenter.new(f, self)
  m << p.notes


  m << p.full_name_block(:top_family_name, :top_given_name, '代表者氏名', size: 32, required: true)
  m << p.full_name_block(:top_family_name_kana, :top_given_name_kana, '代表者フリガナ', size: 32, required: true)


  m << p.full_name_block(:staff_family_name, :staff_given_name, '担当者氏名', size: 32, required: true)
  m << p.full_name_block(:staff_family_name_kana, :staff_given_name_kana, '担当者フリガナ', size: 32, required: true)

  m << p.text_field_block(:postal_code, '郵便番号', size: 7, required: true)
  m << p.drop_down_list_block(:prefecture, '都道府県', Customer::PREFECTURE_NAMES)

 

  m << p.text_field_block(:city, '市区町村', size: 16, required: true)
  m << p.text_field_block(:address1, '町域、番地等', size: 40, required: true)
  m << p.text_field_block(:address2, '建物名、部屋番号等', size: 40)


  m << p.text_field_block(:telephone_number, '電話番号')
  m << p.text_field_block(:mobilephone_number, '携帯番号')
  m << p.text_field_block(:fax_number, 'FAX番号')

  m << p.text_field_block(:email, 'メールアドレス', size: 32 ,required: true)

  m << p.date_field_block(:start_date, '開始日', required: true)
  m << p.date_field_block(:end_date, '終了日', required: false)

  m << p.check_boxes


end %>